---
title: "MRT Stations Masterlist"
author: "Choo Choo Train"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}

# Load required packages
library(tidyverse)   # Contains dplyr (data manipulation), tidyr (data tidying), tibble (data frame manipulation)
library(rvest)       # For HTML and XML web scraping
library(stringr)     # For string manipulation
library(jsonlite)    # For reading JSON data
library(geosphere)   # For Haversine distance
```


```{r}
stations <- read.csv("raw_data/stations.csv")

```

```{r}
df2024_2023 <- read.csv("raw_data/transport_node_train_20232024collated.csv")
```


```{r}
df2024_2023_6_months <- df2024_2023 %>%  separate_rows(PT_CODE, sep = "/") %>% 
  group_by(YEAR_MONTH) %>%
    mutate(is_peak = case_when(TIME_PER_HOUR > 6 & TIME_PER_HOUR < 9 ~ 1,
                             TIME_PER_HOUR > 16 & TIME_PER_HOUR < 20 ~ 1,  
                             TRUE ~ 0)) %>% #turn into peak hour 
  mutate(PT_CODE = case_when(
    PT_CODE == 'BP6' ~ 'DT1',
    TRUE ~ PT_CODE  
  ))%>% 
  ungroup() %>%
  group_by(YEAR_MONTH, DAY_TYPE, PT_CODE, is_peak) %>% 
  summarise(AVG_RIDERS = mean(TOTAL_TAP_IN_VOLUME + TOTAL_TAP_OUT_VOLUME, na.rm = TRUE)) %>%
  ungroup() %>% 
  left_join(stations, by = (c("PT_CODE"= "station_code"))) %>%
  filter(!is.na(line_code)) %>%
  select(line_code,DAY_TYPE, PT_CODE, is_peak, stations, AVG_RIDERS, YEAR_MONTH) %>%
  group_by(YEAR_MONTH, DAY_TYPE, stations, is_peak) %>%
  summarise(AVG_RIDERS = AVG_RIDERS/ n(),
            PT_CODE = PT_CODE) %>%
  ungroup %>%
  rename("station_code" = "PT_CODE"
         , "day_type" = "DAY_TYPE") 


#write.csv(df2024_2023_6_months, "ridership_by_stations_6months.csv", row.names = FALSE)



```



```{r}
file_path2 <- "raw_data/station_data_6months.json"
data3 <- fromJSON(file_path2)
station_data <- data3$data[[1]] %>% unnest(location)
```

("C:/Users/ashle/Desktop/School/Y3S2/dse3101/Project/Data set/OneMap API pull/mrt_stations.csv")
```{r}
mrt_station_coordinates_filepath = "raw_data/mrt_stations.csv"
mrt_station_coordinates <- read.csv(mrt_station_coordinates_filepath)


mrt_data <- mrt_station_coordinates %>%
  
  # Extract MRT or LRT station names
  mutate(Station_Name = tolower(str_remove_all(building, " MRT STATION| \\(.*\\)"))) %>% 
  
  group_by(Station_Name) %>%
  
  summarise(
    # there are instances whereby different mrt stations have different coordinates so we take the central coordinate for simplicity
    longitude = mean(longitude, na.rm = TRUE), 
    latitude = mean(latitude, na.rm = TRUE)) %>%
  
  select(Station_Name, longitude, latitude) %>%
    filter(Station_Name %in% tolower(stations$stations))


```

```{r}

# Define a function to find the closest device for a given MRT station
find_closest_device <- function(mrt_longitude, mrt_latitude, station_data) {
  distance <- Inf
  closest_device_id <- NA
  
  # Loop through each device and compute the distance
  for (station in station_data$id) {
    current_device_data <- station_data[station_data$id == station, ]
    station_longitude <- current_device_data$longitude
    station_latitude <- current_device_data$latitude
    mrt_point <- c(mrt_longitude, mrt_latitude)
    weather_station_point <- c(station_longitude, station_latitude)
    new_distance <- distHaversine(mrt_point, weather_station_point)
    
    # Update the closest device if a smaller distance is found
    if (new_distance < distance) {
      distance <- new_distance
      closest_device_id <- station  # Store just the device ID
    }
  }
  
  return(closest_device_id)  # Return only the ID of the closest device
}

mrt_data <- mrt_data %>%
  rowwise() %>%
  mutate(closest_device = find_closest_device(longitude, latitude, station_data)) %>%
  ungroup() %>%
  select(Station_Name, closest_device) %>%
  mutate(
    Station_Name = gsub(" MRT STATION", "", Station_Name),
    Station_Name = gsub(" ", "", Station_Name)
  ) 
distinct_mrt <- stations %>%
  select(join_station, stations) %>%
  distinct()
allocated_mrt_station <- left_join(distinct_mrt, mrt_data, by = c("join_station" = "Station_Name")) %>% 
  select(stations, join_station, closest_device)

```


Allocation of weather stations to each mrt station
```{r}

data <- fromJSON("raw_data/rainfall_data_6months.json")  # using only 2 days because the data is too big for github

unique_months <- df2024_2023$YEAR_MONTH%>%unique() ##takes all the unique year_month combination from ridership


rain_falldf <- data[2][1] %>% 
  unnest(cols = c(data)) %>% 
  unnest(cols = c(data))%>%
  mutate(
    date = date(timestamp),
  ) %>%
  group_by(date, stationId) %>%
  summarise(`rain_fall(mm)` = replace_na(mean(value, na.rm = TRUE))) %>%
  ungroup() %>%
  mutate(YEAR_MONTH = format(date, "%Y-%m")) %>%
  arrange(date) %>%
  group_by(stationId) %>% ##gets the mean of rainfall for the last 5 days, including the current day
  mutate(
      mean_last_5_days = sapply(1:n(), function(i) {
      current_date <- date[i]
      relevant_rows <- which(date >= (current_date - 4) & date <= current_date) # Get rows from last 5 days (including current date)
      mean(`rain_fall(mm)`[relevant_rows], na.rm = TRUE) #mean 
    })
  ) %>%
  filter(YEAR_MONTH %in% unique_months) # only keep relevant entries


rainfalldf_6months <-left_join(allocated_mrt_station,rain_falldf,  by = c("closest_device" = "stationId"), relationship = "many-to-many") %>%
  group_by(date) %>%
  mutate(`rain_fall(mm)` = ifelse(
    is.na(`rain_fall(mm)`), mean(`rain_fall(mm)`, na.rm=TRUE), `rain_fall(mm)`)
    ) %>% 
  mutate(`rain_fall(mm)` = ifelse(
    is.na(`rain_fall(mm)`), mean(`rain_fall(mm)`, na.rm=TRUE), `rain_fall(mm)`)
    )


```

Save rainfall data
```{r}
#save(rainfalldf_6months, file = "mrt_rainfalldf_daily_6months.RData")

```






